version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: spring_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql1
      MYSQL_DATABASE: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./final
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
      APP_UPLOAD_DIR: /uploads
    volumes:
      - ./uploads:/uploads
    depends_on:
      - db

volumes:
  db_data:
